version: '3.1'

services:

  db:
    image: postgres:9.5-alpine
    restart: unless-stopped 
    container_name: w3s-sql-exercises
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}" #export DB_PASSWORD='<pass>'
      POSTGRES_DB: "w3s_exercises"
    ports:
      - "5432:5432"
    volumes:
      - './init_scripts:/docker-entrypoint-initdb.d'

volumes:
    init_scripts:
